[2022-05-24 21:13:43,725] {processor.py:153} INFO - Started process (PID=35) to work on /opt/airflow/dags/main_dag.py
[2022-05-24 21:13:43,732] {processor.py:641} INFO - Processing file /opt/airflow/dags/main_dag.py for tasks to queue
[2022-05-24 21:13:43,735] {logging_mixin.py:115} INFO - [2022-05-24 21:13:43,735] {dagbag.py:507} INFO - Filling up the DagBag from /opt/airflow/dags/main_dag.py
[2022-05-24 21:13:46,503] {logging_mixin.py:115} INFO - [2022-05-24 21:13:46,490] {dagbag.py:320} ERROR - Failed to import: /opt/airflow/dags/main_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 317, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/main_dag.py", line 5, in <module>
    from etl_functions import *
  File "/opt/airflow/dags/etl_functions.py", line 5, in <module>
    from dotenv import dotenv_values
ModuleNotFoundError: No module named 'dotenv'
[2022-05-24 21:13:46,508] {processor.py:653} WARNING - No viable dags retrieved from /opt/airflow/dags/main_dag.py
[2022-05-24 21:13:46,574] {processor.py:161} INFO - Processing /opt/airflow/dags/main_dag.py took 2.855 seconds
[2022-05-24 21:14:16,999] {processor.py:153} INFO - Started process (PID=102) to work on /opt/airflow/dags/main_dag.py
[2022-05-24 21:14:17,001] {processor.py:641} INFO - Processing file /opt/airflow/dags/main_dag.py for tasks to queue
[2022-05-24 21:14:17,006] {logging_mixin.py:115} INFO - [2022-05-24 21:14:17,006] {dagbag.py:507} INFO - Filling up the DagBag from /opt/airflow/dags/main_dag.py
[2022-05-24 21:14:17,620] {logging_mixin.py:115} INFO - [2022-05-24 21:14:17,612] {dagbag.py:320} ERROR - Failed to import: /opt/airflow/dags/main_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 317, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/main_dag.py", line 5, in <module>
    from etl_functions import *
  File "/opt/airflow/dags/etl_functions.py", line 5, in <module>
    from dotenv import dotenv_values
ModuleNotFoundError: No module named 'dotenv'
[2022-05-24 21:14:17,622] {processor.py:653} WARNING - No viable dags retrieved from /opt/airflow/dags/main_dag.py
[2022-05-24 21:14:17,662] {processor.py:161} INFO - Processing /opt/airflow/dags/main_dag.py took 0.667 seconds
[2022-05-24 21:14:47,903] {processor.py:153} INFO - Started process (PID=169) to work on /opt/airflow/dags/main_dag.py
[2022-05-24 21:14:47,906] {processor.py:641} INFO - Processing file /opt/airflow/dags/main_dag.py for tasks to queue
[2022-05-24 21:14:47,908] {logging_mixin.py:115} INFO - [2022-05-24 21:14:47,907] {dagbag.py:507} INFO - Filling up the DagBag from /opt/airflow/dags/main_dag.py
[2022-05-24 21:14:49,109] {logging_mixin.py:115} INFO - [2022-05-24 21:14:49,098] {dagbag.py:320} ERROR - Failed to import: /opt/airflow/dags/main_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 317, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/main_dag.py", line 5, in <module>
    from etl_functions import *
  File "/opt/airflow/dags/etl_functions.py", line 5, in <module>
    from dotenv import dotenv_values
ModuleNotFoundError: No module named 'dotenv'
[2022-05-24 21:14:49,116] {processor.py:653} WARNING - No viable dags retrieved from /opt/airflow/dags/main_dag.py
[2022-05-24 21:14:49,192] {processor.py:161} INFO - Processing /opt/airflow/dags/main_dag.py took 1.302 seconds
[2022-05-24 21:15:19,534] {processor.py:153} INFO - Started process (PID=239) to work on /opt/airflow/dags/main_dag.py
[2022-05-24 21:15:19,540] {processor.py:641} INFO - Processing file /opt/airflow/dags/main_dag.py for tasks to queue
[2022-05-24 21:15:19,542] {logging_mixin.py:115} INFO - [2022-05-24 21:15:19,541] {dagbag.py:507} INFO - Filling up the DagBag from /opt/airflow/dags/main_dag.py
[2022-05-24 21:15:19,991] {logging_mixin.py:115} INFO - [2022-05-24 21:15:19,986] {dagbag.py:320} ERROR - Failed to import: /opt/airflow/dags/main_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 317, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/main_dag.py", line 5, in <module>
    from etl_functions import *
  File "/opt/airflow/dags/etl_functions.py", line 5, in <module>
    from dotenv import dotenv_values
ModuleNotFoundError: No module named 'dotenv'
[2022-05-24 21:15:19,993] {processor.py:653} WARNING - No viable dags retrieved from /opt/airflow/dags/main_dag.py
[2022-05-24 21:15:20,022] {processor.py:161} INFO - Processing /opt/airflow/dags/main_dag.py took 0.494 seconds
[2022-05-24 21:15:39,978] {processor.py:153} INFO - Started process (PID=298) to work on /opt/airflow/dags/main_dag.py
[2022-05-24 21:15:39,982] {processor.py:641} INFO - Processing file /opt/airflow/dags/main_dag.py for tasks to queue
[2022-05-24 21:15:39,986] {logging_mixin.py:115} INFO - [2022-05-24 21:15:39,985] {dagbag.py:507} INFO - Filling up the DagBag from /opt/airflow/dags/main_dag.py
[2022-05-24 21:15:40,755] {logging_mixin.py:115} INFO - [2022-05-24 21:15:40,742] {dagbag.py:320} ERROR - Failed to import: /opt/airflow/dags/main_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 317, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/main_dag.py", line 5, in <module>
    from etl_functions import *
  File "/opt/airflow/dags/etl_functions.py", line 5, in <module>
    from dotenv import dotenv_values
ModuleNotFoundError: No module named 'dotenv'
[2022-05-24 21:15:40,756] {processor.py:653} WARNING - No viable dags retrieved from /opt/airflow/dags/main_dag.py
[2022-05-24 21:15:40,792] {processor.py:161} INFO - Processing /opt/airflow/dags/main_dag.py took 0.828 seconds
[2022-05-24 21:15:45,972] {processor.py:153} INFO - Started process (PID=300) to work on /opt/airflow/dags/main_dag.py
[2022-05-24 21:15:45,974] {processor.py:641} INFO - Processing file /opt/airflow/dags/main_dag.py for tasks to queue
[2022-05-24 21:15:45,977] {logging_mixin.py:115} INFO - [2022-05-24 21:15:45,977] {dagbag.py:507} INFO - Filling up the DagBag from /opt/airflow/dags/main_dag.py
[2022-05-24 21:15:46,415] {logging_mixin.py:115} INFO - [2022-05-24 21:15:46,412] {dagbag.py:320} ERROR - Failed to import: /opt/airflow/dags/main_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 317, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/main_dag.py", line 5, in <module>
    from etl_functions import *
  File "/opt/airflow/dags/etl_functions.py", line 5, in <module>
    from dotenv import dotenv_values
ModuleNotFoundError: No module named 'dotenv'
[2022-05-24 21:15:46,416] {processor.py:653} WARNING - No viable dags retrieved from /opt/airflow/dags/main_dag.py
[2022-05-24 21:15:46,436] {processor.py:161} INFO - Processing /opt/airflow/dags/main_dag.py took 0.476 seconds
[2022-05-24 21:16:17,293] {processor.py:153} INFO - Started process (PID=366) to work on /opt/airflow/dags/main_dag.py
[2022-05-24 21:16:17,295] {processor.py:641} INFO - Processing file /opt/airflow/dags/main_dag.py for tasks to queue
[2022-05-24 21:16:17,297] {logging_mixin.py:115} INFO - [2022-05-24 21:16:17,297] {dagbag.py:507} INFO - Filling up the DagBag from /opt/airflow/dags/main_dag.py
[2022-05-24 21:16:17,844] {logging_mixin.py:115} INFO - [2022-05-24 21:16:17,838] {dagbag.py:320} ERROR - Failed to import: /opt/airflow/dags/main_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 317, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/main_dag.py", line 5, in <module>
    from etl_functions import *
  File "/opt/airflow/dags/etl_functions.py", line 5, in <module>
    from dotenv import dotenv_values
ModuleNotFoundError: No module named 'dotenv'
[2022-05-24 21:16:17,845] {processor.py:653} WARNING - No viable dags retrieved from /opt/airflow/dags/main_dag.py
[2022-05-24 21:16:17,870] {processor.py:161} INFO - Processing /opt/airflow/dags/main_dag.py took 0.585 seconds
[2022-05-24 21:16:48,168] {processor.py:153} INFO - Started process (PID=433) to work on /opt/airflow/dags/main_dag.py
[2022-05-24 21:16:48,170] {processor.py:641} INFO - Processing file /opt/airflow/dags/main_dag.py for tasks to queue
[2022-05-24 21:16:48,173] {logging_mixin.py:115} INFO - [2022-05-24 21:16:48,172] {dagbag.py:507} INFO - Filling up the DagBag from /opt/airflow/dags/main_dag.py
[2022-05-24 21:16:48,519] {logging_mixin.py:115} INFO - [2022-05-24 21:16:48,516] {dagbag.py:320} ERROR - Failed to import: /opt/airflow/dags/main_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 317, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/main_dag.py", line 5, in <module>
    from etl_functions import *
  File "/opt/airflow/dags/etl_functions.py", line 6, in <module>
    from mysql.connector import connect, Error
ModuleNotFoundError: No module named 'mysql'
[2022-05-24 21:16:48,520] {processor.py:653} WARNING - No viable dags retrieved from /opt/airflow/dags/main_dag.py
[2022-05-24 21:16:48,534] {processor.py:161} INFO - Processing /opt/airflow/dags/main_dag.py took 0.372 seconds
[2022-05-24 21:17:19,003] {processor.py:153} INFO - Started process (PID=493) to work on /opt/airflow/dags/main_dag.py
[2022-05-24 21:17:19,005] {processor.py:641} INFO - Processing file /opt/airflow/dags/main_dag.py for tasks to queue
[2022-05-24 21:17:19,007] {logging_mixin.py:115} INFO - [2022-05-24 21:17:19,007] {dagbag.py:507} INFO - Filling up the DagBag from /opt/airflow/dags/main_dag.py
[2022-05-24 21:17:19,642] {logging_mixin.py:115} INFO - [2022-05-24 21:17:19,632] {dagbag.py:320} ERROR - Failed to import: /opt/airflow/dags/main_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 317, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/main_dag.py", line 5, in <module>
    from etl_functions import *
  File "/opt/airflow/dags/etl_functions.py", line 7, in <module>
    from flatten_json import flatten
ModuleNotFoundError: No module named 'flatten_json'
[2022-05-24 21:17:19,644] {processor.py:653} WARNING - No viable dags retrieved from /opt/airflow/dags/main_dag.py
[2022-05-24 21:17:19,688] {processor.py:161} INFO - Processing /opt/airflow/dags/main_dag.py took 0.690 seconds
[2022-05-24 21:17:50,017] {processor.py:153} INFO - Started process (PID=560) to work on /opt/airflow/dags/main_dag.py
[2022-05-24 21:17:50,020] {processor.py:641} INFO - Processing file /opt/airflow/dags/main_dag.py for tasks to queue
[2022-05-24 21:17:50,025] {logging_mixin.py:115} INFO - [2022-05-24 21:17:50,023] {dagbag.py:507} INFO - Filling up the DagBag from /opt/airflow/dags/main_dag.py
[2022-05-24 21:17:50,372] {logging_mixin.py:115} INFO - [2022-05-24 21:17:50,368] {dagbag.py:320} ERROR - Failed to import: /opt/airflow/dags/main_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 317, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/main_dag.py", line 5, in <module>
    from etl_functions import *
  File "/opt/airflow/dags/etl_functions.py", line 7, in <module>
    from flatten_json import flatten
ModuleNotFoundError: No module named 'flatten_json'
[2022-05-24 21:17:50,373] {processor.py:653} WARNING - No viable dags retrieved from /opt/airflow/dags/main_dag.py
[2022-05-24 21:17:50,390] {processor.py:161} INFO - Processing /opt/airflow/dags/main_dag.py took 0.380 seconds
[2022-05-24 21:18:21,016] {processor.py:153} INFO - Started process (PID=627) to work on /opt/airflow/dags/main_dag.py
[2022-05-24 21:18:21,019] {processor.py:641} INFO - Processing file /opt/airflow/dags/main_dag.py for tasks to queue
[2022-05-24 21:18:21,021] {logging_mixin.py:115} INFO - [2022-05-24 21:18:21,021] {dagbag.py:507} INFO - Filling up the DagBag from /opt/airflow/dags/main_dag.py
[2022-05-24 21:18:21,494] {logging_mixin.py:115} INFO - [2022-05-24 21:18:21,493] {dagbag.py:320} ERROR - Failed to import: /opt/airflow/dags/main_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 317, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/main_dag.py", line 22, in <module>
    python_callable= edamam_get
NameError: name 'edamam_get' is not defined
[2022-05-24 21:18:21,496] {processor.py:653} WARNING - No viable dags retrieved from /opt/airflow/dags/main_dag.py
[2022-05-24 21:18:21,512] {processor.py:161} INFO - Processing /opt/airflow/dags/main_dag.py took 0.506 seconds
[2022-05-24 21:18:51,977] {processor.py:153} INFO - Started process (PID=694) to work on /opt/airflow/dags/main_dag.py
[2022-05-24 21:18:51,982] {processor.py:641} INFO - Processing file /opt/airflow/dags/main_dag.py for tasks to queue
[2022-05-24 21:18:51,985] {logging_mixin.py:115} INFO - [2022-05-24 21:18:51,985] {dagbag.py:507} INFO - Filling up the DagBag from /opt/airflow/dags/main_dag.py
[2022-05-24 21:18:52,436] {logging_mixin.py:115} INFO - [2022-05-24 21:18:52,434] {dagbag.py:320} ERROR - Failed to import: /opt/airflow/dags/main_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 317, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/main_dag.py", line 5, in <module>
    from etl_functions import *
  File "/opt/airflow/dags/etl_functions.py", line 7, in <module>
    from flatten_json import flatten
ModuleNotFoundError: No module named 'flatten_json'
[2022-05-24 21:18:52,440] {processor.py:653} WARNING - No viable dags retrieved from /opt/airflow/dags/main_dag.py
[2022-05-24 21:18:52,461] {processor.py:161} INFO - Processing /opt/airflow/dags/main_dag.py took 0.491 seconds
[2022-05-24 21:19:22,607] {processor.py:153} INFO - Started process (PID=753) to work on /opt/airflow/dags/main_dag.py
[2022-05-24 21:19:22,610] {processor.py:641} INFO - Processing file /opt/airflow/dags/main_dag.py for tasks to queue
[2022-05-24 21:19:22,613] {logging_mixin.py:115} INFO - [2022-05-24 21:19:22,613] {dagbag.py:507} INFO - Filling up the DagBag from /opt/airflow/dags/main_dag.py
[2022-05-24 21:19:23,044] {logging_mixin.py:115} INFO - [2022-05-24 21:19:23,041] {dagbag.py:320} ERROR - Failed to import: /opt/airflow/dags/main_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 317, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/main_dag.py", line 5, in <module>
    from etl_functions import *
  File "/opt/airflow/dags/etl_functions.py", line 7, in <module>
    from flatten_json import flatten
ModuleNotFoundError: No module named 'flatten_json'
[2022-05-24 21:19:23,045] {processor.py:653} WARNING - No viable dags retrieved from /opt/airflow/dags/main_dag.py
[2022-05-24 21:19:23,065] {processor.py:161} INFO - Processing /opt/airflow/dags/main_dag.py took 0.467 seconds
[2022-05-24 21:19:53,762] {processor.py:153} INFO - Started process (PID=823) to work on /opt/airflow/dags/main_dag.py
[2022-05-24 21:19:53,764] {processor.py:641} INFO - Processing file /opt/airflow/dags/main_dag.py for tasks to queue
[2022-05-24 21:19:53,765] {logging_mixin.py:115} INFO - [2022-05-24 21:19:53,765] {dagbag.py:507} INFO - Filling up the DagBag from /opt/airflow/dags/main_dag.py
[2022-05-24 21:19:54,170] {logging_mixin.py:115} INFO - [2022-05-24 21:19:54,163] {dagbag.py:320} ERROR - Failed to import: /opt/airflow/dags/main_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 317, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/main_dag.py", line 5, in <module>
    from etl_functions import *
  File "/opt/airflow/dags/etl_functions.py", line 7, in <module>
    from flatten_json import flatten
ModuleNotFoundError: No module named 'flatten_json'
[2022-05-24 21:19:54,171] {processor.py:653} WARNING - No viable dags retrieved from /opt/airflow/dags/main_dag.py
[2022-05-24 21:19:54,189] {processor.py:161} INFO - Processing /opt/airflow/dags/main_dag.py took 0.433 seconds
[2022-05-24 21:20:24,465] {processor.py:153} INFO - Started process (PID=893) to work on /opt/airflow/dags/main_dag.py
[2022-05-24 21:20:24,468] {processor.py:641} INFO - Processing file /opt/airflow/dags/main_dag.py for tasks to queue
[2022-05-24 21:20:24,470] {logging_mixin.py:115} INFO - [2022-05-24 21:20:24,470] {dagbag.py:507} INFO - Filling up the DagBag from /opt/airflow/dags/main_dag.py
[2022-05-24 21:20:24,907] {logging_mixin.py:115} INFO - [2022-05-24 21:20:24,901] {dagbag.py:320} ERROR - Failed to import: /opt/airflow/dags/main_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 317, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/main_dag.py", line 5, in <module>
    from etl_functions import *
  File "/opt/airflow/dags/etl_functions.py", line 7, in <module>
    from flatten_json import flatten
ModuleNotFoundError: No module named 'flatten_json'
[2022-05-24 21:20:24,910] {processor.py:653} WARNING - No viable dags retrieved from /opt/airflow/dags/main_dag.py
[2022-05-24 21:20:24,933] {processor.py:161} INFO - Processing /opt/airflow/dags/main_dag.py took 0.477 seconds
[2022-05-24 21:20:55,252] {processor.py:153} INFO - Started process (PID=963) to work on /opt/airflow/dags/main_dag.py
[2022-05-24 21:20:55,255] {processor.py:641} INFO - Processing file /opt/airflow/dags/main_dag.py for tasks to queue
[2022-05-24 21:20:55,256] {logging_mixin.py:115} INFO - [2022-05-24 21:20:55,256] {dagbag.py:507} INFO - Filling up the DagBag from /opt/airflow/dags/main_dag.py
[2022-05-24 21:20:55,517] {logging_mixin.py:115} INFO - [2022-05-24 21:20:55,514] {dagbag.py:320} ERROR - Failed to import: /opt/airflow/dags/main_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 317, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/main_dag.py", line 5, in <module>
    from etl_functions import *
  File "/opt/airflow/dags/etl_functions.py", line 7, in <module>
    from flatten_json import flatten
ModuleNotFoundError: No module named 'flatten_json'
[2022-05-24 21:20:55,517] {processor.py:653} WARNING - No viable dags retrieved from /opt/airflow/dags/main_dag.py
[2022-05-24 21:20:55,531] {processor.py:161} INFO - Processing /opt/airflow/dags/main_dag.py took 0.282 seconds
[2022-05-24 21:21:25,672] {processor.py:153} INFO - Started process (PID=1029) to work on /opt/airflow/dags/main_dag.py
[2022-05-24 21:21:25,674] {processor.py:641} INFO - Processing file /opt/airflow/dags/main_dag.py for tasks to queue
[2022-05-24 21:21:25,676] {logging_mixin.py:115} INFO - [2022-05-24 21:21:25,676] {dagbag.py:507} INFO - Filling up the DagBag from /opt/airflow/dags/main_dag.py
[2022-05-24 21:21:26,047] {logging_mixin.py:115} INFO - [2022-05-24 21:21:26,044] {dagbag.py:320} ERROR - Failed to import: /opt/airflow/dags/main_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 317, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/main_dag.py", line 5, in <module>
    from etl_functions import *
  File "/opt/airflow/dags/etl_functions.py", line 7, in <module>
    from flatten_json import flatten
ModuleNotFoundError: No module named 'flatten_json'
[2022-05-24 21:21:26,049] {processor.py:653} WARNING - No viable dags retrieved from /opt/airflow/dags/main_dag.py
[2022-05-24 21:21:26,064] {processor.py:161} INFO - Processing /opt/airflow/dags/main_dag.py took 0.396 seconds
[2022-05-24 21:21:56,246] {processor.py:153} INFO - Started process (PID=1087) to work on /opt/airflow/dags/main_dag.py
[2022-05-24 21:21:56,248] {processor.py:641} INFO - Processing file /opt/airflow/dags/main_dag.py for tasks to queue
[2022-05-24 21:21:56,249] {logging_mixin.py:115} INFO - [2022-05-24 21:21:56,249] {dagbag.py:507} INFO - Filling up the DagBag from /opt/airflow/dags/main_dag.py
[2022-05-24 21:21:56,614] {logging_mixin.py:115} INFO - [2022-05-24 21:21:56,611] {dagbag.py:320} ERROR - Failed to import: /opt/airflow/dags/main_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 317, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/main_dag.py", line 5, in <module>
    from etl_functions import *
  File "/opt/airflow/dags/etl_functions.py", line 7, in <module>
    from flatten_json import flatten
ModuleNotFoundError: No module named 'flatten_json'
[2022-05-24 21:21:56,615] {processor.py:653} WARNING - No viable dags retrieved from /opt/airflow/dags/main_dag.py
[2022-05-24 21:21:56,630] {processor.py:161} INFO - Processing /opt/airflow/dags/main_dag.py took 0.389 seconds
[2022-05-24 21:22:27,115] {processor.py:153} INFO - Started process (PID=1160) to work on /opt/airflow/dags/main_dag.py
[2022-05-24 21:22:27,118] {processor.py:641} INFO - Processing file /opt/airflow/dags/main_dag.py for tasks to queue
[2022-05-24 21:22:27,120] {logging_mixin.py:115} INFO - [2022-05-24 21:22:27,120] {dagbag.py:507} INFO - Filling up the DagBag from /opt/airflow/dags/main_dag.py
[2022-05-24 21:22:27,609] {logging_mixin.py:115} INFO - [2022-05-24 21:22:27,603] {dagbag.py:320} ERROR - Failed to import: /opt/airflow/dags/main_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 317, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/main_dag.py", line 5, in <module>
    from etl_functions import *
  File "/opt/airflow/dags/etl_functions.py", line 7, in <module>
    from flatten_json import flatten
ModuleNotFoundError: No module named 'flatten_json'
[2022-05-24 21:22:27,611] {processor.py:653} WARNING - No viable dags retrieved from /opt/airflow/dags/main_dag.py
[2022-05-24 21:22:27,638] {processor.py:161} INFO - Processing /opt/airflow/dags/main_dag.py took 0.530 seconds
